### ISSUE TITLE
Добавить Repository Pattern

### ISSUE THREAD

**Issue by Focus1337** [Boobl1k/dekoffee#10]
_Originally posted by @Boobl1k in https://github.com/Boobl1k/dekoffee/pull/3#discussion_r1183132213_

**Comment by Boobl1k** [comment]
ишью опционален, как по мне лучше не тратить на это время

**Comment by Focus1337** [comment]
Ишью более не опционален. Может помочь в сдачи проекта.

**Comment by Focus1337** [comment]
Было сделано в рамках PR #35.
(забыл указать)
