### ISSUE TITLE
Заменить OpenIddict на кастомную авторизацию

### ISSUE THREAD

**Issue by Focus1337** [Boobl1k/dekoffee#11]
для чего был использован OpenIdDict? Возможно стоило бы реализовать кастомную авторизацию

_Originally posted by @Boobl1k in https://github.com/Boobl1k/dekoffee/pull/3#discussion_r1183134649_

**Comment by Boobl1k** [comment]
такого решения мы не принимали. Для меня сейчас оптимальным решением выглядит оставить OpenIdDict и использовать нормальные роли

**Comment by Boobl1k** [comment]
приятно решение оставить как есть
