### ISSUE TITLE
Изменить сущности

### ISSUE THREAD

**Issue by Focus1337** [Boobl1k/dekoffee#12]
Изменить сущности.

- User
Добавить новое поле Role (enum: Admin, Executor).
- Address
Убрать навигацию к User. 
Добавить поле Section (подъезд, секция).
- Order
Добавить поле: указанное пользователем время для доставки (период): LowerSelectedTime, UpperSelectedTime. 
Изменить Status: InCooking -> Cooking, Processing -> Accepted (оплачено, принято к работе).
Добавить Status: Packing (в сборке).
- CartProduct
Добавить поле Count. Нужно для подсчета кол-ва определенного товара в корзине. 
- Courier
Переименовать сущность в Executor. Является курьером или администратором заведения (определенной точки). Также у них одинаковые возможности.

_Originally posted by @Focus1337 in https://github.com/Boobl1k/dekoffee/issues/3#issuecomment-1537212164_

**Comment by Boobl1k** [comment]
приятно решение оставить openIdDict и использовать нормальные роли вместо костыля в виде поля в энтити. В User поле Role не будет добавлено
