### ISSUE TITLE
в docker-compose насрано

### ISSUE THREAD

**Issue by Boobl1k** [Boobl1k/dekoffee#14]
для чего там rabbitmq?

**Comment by Focus1337** [comment]
По изначальному плану должен был использоваться RabbitMQ, однако от него отказались совсем недавно. 
Можно удалить оттуда.

**Comment by Focus1337** [comment]
btw ревьюер даун, раз замерджил и только потом заметил [🤦‍♂️

**Comment by Boobl1k** [comment]
стоит поменять названия сервисов и не использовать сомнительные порты

**Comment by Focus1337** [comment]
Названия сервисов соответствуют HLD (PR https://github.com/Boobl1k/dekoffee/pull/1). Если считаешь, что нужно изменить, предложи название. Так же не будет лишним напомнить, что принцип работы и взаимодействия сервисов друг с другом с недавних пор поменялся - сейчас у нас только один сервис. Так что в какой-то степени название Main уже не соответствует изначальному названию.

Про сомнительность портов: для кого-то они сомнительные, для кого-то нет. В чем их сомнительность? Почему мы должны их менять? В требованиях не указаны порты. Если только сомнительность заключается в том, что используется стандартный порт 81.

**Comment by Boobl1k** [comment]
давай назовем api
мне не нравится порт 81, потому что был случай когда на этом порте кое у кого не запустился наш сервис на его машине. Давай для api использовать 5xxx, для веба 3xxx

**Comment by Boobl1k** [comment]
сделал эти изменения в #16

**Comment by Focus1337** [comment]
Применил изменения без согласия остальных членов команды.
Некрасивый поступок.

**Comment by Boobl1k** [comment]
а для чего я у тебя ревью попросил, тиммейт ты мой любимый?

**Comment by Focus1337** [comment]
Изменения приняты. Закрываю.
api - 5000
web - 3000
db - 5432
