### ISSUE TITLE
в репозитории неудачное решение

### ISSUE THREAD

**Issue by Boobl1k** [Boobl1k/dekoffee#15]
что делает sln файл на уровне src/? может стоит перемесить в Services? и почему вообще все папки с большой буквы??

**Comment by Focus1337** [comment]
.sln файл находится там, где и должен находиться. Потому что этот файл не относится конкретно к .NET приложениям, а также не относится конкретно к сервисам. Смысл .sln файла как раз-таки в том, чтобы содержать ВСЁ решение проекта, включая и Web, и Services. А также, по-хорошему, файлы конфигурации: docker-compose, .env и др.

Папки и не обязаны быть с маленькой буквы.  Если обратить внимание на референсное приложение eShopOnContainers от Microsoft, то видно, что они и придерживаются той же идеи разделения и наименования папок, что и в этом проекте.

**Comment by Boobl1k** [comment]
может ты и прав. можно закрывать
