### ISSUE TITLE
automapper is trash?

### ISSUE THREAD

**Issue by Boobl1k** [Boobl1k/dekoffee#23]
я считаю что стоит отказаться от использования автомаппера. В настоящий момент уже существуют костыли для поздней инициализации ненулабельных полей (например OrderController 91), и станет еще больше если мы начнем следить за null safety

**Comment by Boobl1k** [comment]
issue является блокером для #12

**Comment by Focus1337** [comment]
Я абсолютно не согласен с решением, предоставленным в PR #24.
При использовании AutoMapper всё было намного лучше.

**Comment by Focus1337** [comment]
Было решено оставить решение из PR #24.
