### ISSUE TITLE
Расписать требования для сервиса Main

### ISSUE THREAD

**Issue by Focus1337** [Boobl1k/dekoffee#5]
у нас непонятны требования для бэка. Какие юзкейсы мы реализовываем? Исходя из каких рассуждений ты пишешь функционал?
Проблема в том, что сами юзкейсы для продукта не расписаны. Если смотреть на то, что мы показали на курсе, вообще не расписано и нереалистично
Думаю стоит минимально расписать что для чего и как будет реализовано

_Originally posted by @Boobl1k in https://github.com/Boobl1k/dekoffee/issues/3#issuecomment-1528784242_

**Comment by Boobl1k** [comment]
требования расписаны
https://docs.google.com/document/d/1UgvYnFsNUd4wgDqcqEdzEhbNf_8NiPCBkvYWsRBsMNM/edit
