### ISSUE TITLE
Нужно исправить эндпоинты

### ISSUE THREAD

**Issue by Focus1337** [Boobl1k/dekoffee#9]
Нужно исправить эндпоинты:

- Должно использоваться множественное число в названии контроллера:
**/orders/{id}/cancel/**
- Должен использоваться kebab-case, а не CamelCase:
**/admins/orders/{id}/change-status/**
- Должен быть правильный порядок в эндпоинтах: 
**/admin/orders/{id}/change-status/**

_Originally posted by @Focus1337 in https://github.com/Boobl1k/dekoffee/issues/3#issuecomment-1537205650_

**Comment by Boobl1k** [comment]
А как мы раньше без роутинга обходились...

**Comment by Focus1337** [comment]
Сделал изменения в PR: #20
